---
version: "3.7"
services:

  # ---------------------------------------------------------------------
  # | Nginx-Service                                                     |
  # ---------------------------------------------------------------------
  nginx:
    build:
      context: ../backend/static
      dockerfile: static.Dockerfile
    container_name: static
    restart: unless-stopped
    volumes:
      - ../frontend/static/dist:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.static.entrypoints=web
      - traefik.http.routers.static.middlewares=test-redirectscheme
      - traefik.http.routers.static-secure.entrypoints=websecure
      - traefik.http.routers.static-secure.tls.certresolver=myresolver
      - traefik.http.routers.static-secure.tls=true
      - traefik.http.routers.static-secure.middlewares=test-compress,test-redirectscheme
      # Services
      - traefik.http.services.static-secure.loadbalancer.server.port=80
      # Middlewares
      - traefik.http.middlewares.test-compress.compress=true
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true
      - traefik.http.middlewares.test-redirectscheme.redirectscheme.port=443
